apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::668183236892:role/eksctl-roboshop-dev-addon-iamserviceaccount-r-Role1-ICODx8GwIjJ0
  creationTimestamp: "2025-12-18T16:37:13Z"
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: secret-reader
  namespace: roboshop
  resourceVersion: "115424"
  uid: b251d1e7-52da-4e8b-aa64-7af6d266b38c
